import os
import psycopg2
from psycopg2.extras import RealDictCursor
from dotenv import load_dotenv
import logging
import json

# This file is used to centralize functions
# Thanks to this, we will be able to call these functions in other files 


# We load the environment variables
load_dotenv()

# Retrieving the Neon URL from the .env file
DB_CONNECTION_STRING = os.getenv("DATABASE_URL")

# This class is used to connect to and read/write to NEonDB
class DatabaseManager:
    def __init__(self):
        # Database connection
        try:
            # Open the connection with NEonDB
            self.conn = psycopg2.connect(DB_CONNECTION_STRING)
            self.conn.autocommit = True  # Automatically validates requests, no need to use .commit()
        except Exception as e:
            # raises an error if the connection fails, to avoid a silent error
            logging.error(f"Error of connexion: {e}")
            raise e

    # Metadata backup method
    def insert_image(self, batch_id, camera_name, s3_path):
        # New is hardcoded because the status will always be new upon insertion
        """Save a new image"""
        query = """
        INSERT INTO images (batch_id, camera_name, s3_path, status)
        VALUES (%s, %s, %s, 'NEW')
        RETURNING id;
        """
        try:
            # Block to execute "query"
            with self.conn.cursor() as cur:  # With to ensure the cursor is closed after the request
                cur.execute(query, (batch_id, camera_name, s3_path))  # inject the three values ​​in place of the %s
                image_id = cur.fetchone()[0]  # Take the ID generated by PostgreSQL
                return image_id
        except Exception as e:
            logging.error(f"Error insert_image: {e}")
            return None

    # Method to retrieve the queue
    def get_pending_images(self, limit=10):
        """Retrieve the pending images"""
        query = """
        SELECT * FROM images 
        WHERE status = 'NEW' 
        ORDER BY captured_at ASC 
        LIMIT %s;
        """
        try:
            # First, we get the information from a dictionary.
            with self.conn.cursor(cursor_factory=RealDictCursor) as cur:  # RealDictCursor return a dictionary
                cur.execute(query, (limit,))
                # Then we group them into a list
                return cur.fetchall()  
        except Exception as e:
            logging.error(f"Error get_pending_images: {e}")
            return []  # Since it's a loop, we return a list to prevent it from crashing

    # Updated with model predictions
    def update_prediction(self, image_id, fire_detected, confidence, bbox):
        """Updates the AI ​​result"""
        query = """
        UPDATE images 
        SET status = 'PROCESSED', 
            fire_detected = %s, 
            confidence = %s, 
            bbox = %s
        WHERE id = %s;
        """
        try:
            # We convert the list to JSON because bbox is a Python list
            # and PostgreSQL cannot store lists in a column
            bbox_json = json.dumps(bbox)
            with self.conn.cursor() as cur:
                cur.execute(query, (fire_detected, confidence, bbox_json, image_id))
        except Exception as e:
            logging.error(f"Error update_prediction: {e}")

    # Close the connection with NEonDB
    def close(self):
        if self.conn:
            self.conn.close()

    # Method for retrieving images that have already been analyzed
    # The only difference with get_pending_images is that it retrieves the "processed" images
    def get_recent_processed_images(self, limit=100):
        """Retrieve the already processed images"""
        query = """
        SELECT * FROM images 
        WHERE status = 'PROCESSED' 
        ORDER BY captured_at ASC 
        LIMIT %s;
        """
        try:
            with self.conn.cursor(cursor_factory=RealDictCursor) as cur:
                cur.execute(query, (limit,))
                return cur.fetchall()
        except Exception as e:
            logging.error(f"Error get_recent_processed_images: {e}")
            return []
